// <auto-generated />
using System;
using AeroHubAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AeroHubAPI.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AeroHubAPI.Models.Carteira", b =>
                {
                    b.Property<int>("IdCarteira")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("idCarteira");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdCarteira"));

                    b.Property<DateTime>("DataCriacaoCarteira")
                        .HasColumnType("datetime2")
                        .HasColumnName("dataCriacaoCarteira");

                    b.Property<int>("IdUsuario")
                        .HasColumnType("int")
                        .HasColumnName("idUsuario");

                    b.Property<decimal>("PendenteReceberCarteira")
                        .HasColumnType("DECIMAL(15,2)")
                        .HasColumnName("pendenteReceberCarteira");

                    b.Property<decimal>("SaldoBloqueadoCarteira")
                        .HasColumnType("DECIMAL(15,2)")
                        .HasColumnName("saldoBloqueadoCarteira");

                    b.Property<decimal>("SaldoContratanteCarteira")
                        .HasColumnType("DECIMAL(15,2)")
                        .HasColumnName("saldoContratanteCarteira");

                    b.Property<decimal>("SaldoPilotoCarteira")
                        .HasColumnType("DECIMAL(15,2)")
                        .HasColumnName("saldoPilotoCarteira");

                    b.Property<decimal>("TotalGastoContratanteCarteira")
                        .HasColumnType("DECIMAL(15,2)")
                        .HasColumnName("totalGastoContratanteCarteira");

                    b.Property<decimal>("TotalRecebidoPilotoCarteira")
                        .HasColumnType("DECIMAL(15,2)")
                        .HasColumnName("totalRecebidoPilotoCarteira");

                    b.Property<decimal>("TotalSacadoPilotoCarteira")
                        .HasColumnType("DECIMAL(15,2)")
                        .HasColumnName("totalSacadoPilotoCarteira");

                    b.Property<decimal>("ValorMinimoSaqueCarteira")
                        .HasColumnType("DECIMAL(15,2)")
                        .HasColumnName("valorMinimoSaqueCarteira");

                    b.HasKey("IdCarteira");

                    b.HasIndex("IdUsuario")
                        .IsUnique();

                    b.ToTable("Carteira");
                });

            modelBuilder.Entity("AeroHubAPI.Models.Contratante", b =>
                {
                    b.Property<int>("IdContratante")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("idContratante");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdContratante"));

                    b.Property<DateTime?>("DataAtualizacaoContratante")
                        .HasColumnType("datetime2")
                        .HasColumnName("dataAtualizacaoContratante");

                    b.Property<DateTime>("DataCriacaoContratante")
                        .HasColumnType("datetime2")
                        .HasColumnName("dataCriacaoContratante");

                    b.Property<int>("IdPessoa")
                        .HasColumnType("int")
                        .HasColumnName("idPessoa");

                    b.Property<int>("IdUsuario")
                        .HasColumnType("int")
                        .HasColumnName("idUsuario");

                    b.Property<decimal?>("PercentualConclusaoPerfilContratante")
                        .HasColumnType("DECIMAL(5,2)")
                        .HasColumnName("percentualConclusaoPerfilContratante");

                    b.Property<bool>("PerfilCompletoContratante")
                        .HasColumnType("bit")
                        .HasColumnName("perfilCompletoContratante");

                    b.Property<bool>("PlanoPremiumAtivadoContratante")
                        .HasColumnType("bit")
                        .HasColumnName("planoPremiumAtivadoContratante");

                    b.Property<DateTime?>("PremiumDesdeContratante")
                        .HasColumnType("datetime2")
                        .HasColumnName("premimDesdeContratante");

                    b.Property<string>("SetorAtuacaoContratante")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("setorAtuacaoContratante");

                    b.Property<string>("SobreMimContratante")
                        .HasColumnType("TEXT")
                        .HasColumnName("sobreMimContratante");

                    b.Property<string>("StatusContaContratante")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("statusContaContratante");

                    b.Property<string>("TituloProfissionalContratante")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("tituloProfissionalContratante");

                    b.HasKey("IdContratante");

                    b.HasIndex("IdPessoa")
                        .IsUnique();

                    b.HasIndex("IdUsuario")
                        .IsUnique();

                    b.ToTable("Contratante");
                });

            modelBuilder.Entity("AeroHubAPI.Models.DocumentoPessoa", b =>
                {
                    b.Property<int>("IdDocumentoPessoa")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("idDocumentoPessoa");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdDocumentoPessoa"));

                    b.Property<string>("ContratantoSocialCnpjDocumentoPessoa")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("contratantoSocialCnpjDocumentoPessoa");

                    b.Property<string>("DocumentoCnpjDocumentoPessoa")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("documentoCnpjDocumentoPessoa");

                    b.Property<string>("DocumentoFrenteCpfDocumentoPessoa")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("documentoFrenteCpfDocumentoPessoa");

                    b.Property<string>("DocumentoVersoCpfDocumentoPessoa")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("documentoVersoCpfDocumentoPessoa");

                    b.Property<string>("FotoPerfilPessoaDocumentoPessoa")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("fotoPerfilPessoaDocumentoPessoa");

                    b.Property<int>("IdPessoa")
                        .HasColumnType("int")
                        .HasColumnName("idPessoa");

                    b.Property<string>("LogoCnpjDocumentoPessoa")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("logoCnpjDocumentoPessoa");

                    b.HasKey("IdDocumentoPessoa");

                    b.HasIndex("IdPessoa")
                        .IsUnique();

                    b.ToTable("DocumentoPessoa");
                });

            modelBuilder.Entity("AeroHubAPI.Models.Endereco", b =>
                {
                    b.Property<int>("IdEndereco")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("idEndereco");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdEndereco"));

                    b.Property<string>("BairroEndereco")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("bairroEndereco");

                    b.Property<string>("CepEndereco")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("cepEndereco");

                    b.Property<string>("CidadeEndereco")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("cidadeEndereco");

                    b.Property<string>("ComplementoEndereco")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("complementoEndereco");

                    b.Property<DateTime>("DataCriacaoEndereco")
                        .HasColumnType("datetime2")
                        .HasColumnName("dataCriacaoEndereco");

                    b.Property<string>("EstadoEndereco")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("nvarchar(2)")
                        .HasColumnName("estadoEndereco");

                    b.Property<int>("IdPessoa")
                        .HasColumnType("int")
                        .HasColumnName("idPessoa");

                    b.Property<string>("LogradouroEndereco")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("logradouroEndereco");

                    b.Property<string>("NumeroEndereco")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("numeroEndereco");

                    b.HasKey("IdEndereco");

                    b.HasIndex("IdPessoa");

                    b.ToTable("Endereco");
                });

            modelBuilder.Entity("AeroHubAPI.Models.Pessoa", b =>
                {
                    b.Property<int>("IdPessoa")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("idPessoa");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdPessoa"));

                    b.Property<string>("CnpjCnpjPessoa")
                        .HasMaxLength(18)
                        .HasColumnType("nvarchar(18)")
                        .HasColumnName("cnpjCnpjPessoa");

                    b.Property<string>("ContextoPessoa")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("contextoPessoa");

                    b.Property<string>("CpfCpfPessoa")
                        .HasMaxLength(14)
                        .HasColumnType("nvarchar(14)")
                        .HasColumnName("cpfCpfPessoa");

                    b.Property<DateTime?>("DataAtualizacaoPessoa")
                        .HasColumnType("datetime2")
                        .HasColumnName("dataAtualizacaoPessoa");

                    b.Property<DateTime>("DataCriacaoPessoa")
                        .HasColumnType("datetime2")
                        .HasColumnName("dataCriacaoPessoa");

                    b.Property<DateTime?>("DataNascimentoCpfPessoa")
                        .HasColumnType("datetime2")
                        .HasColumnName("dataNascimentoCpfPessoa");

                    b.Property<string>("GeneroCpfPessoa")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("generoCpfPessoa");

                    b.Property<int>("IdUsuario")
                        .HasColumnType("int")
                        .HasColumnName("idUsuario");

                    b.Property<string>("InscricaoEstadualCnpjPessoa")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("inscricaoEstadualCnpjPessoa");

                    b.Property<string>("InscricaoMunicipalCnpjPessoa")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("inscricaoMunicipalCnpjPessoa");

                    b.Property<string>("NomeCompletoCpfPessoa")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("nomeCompletoCpfPessoa");

                    b.Property<string>("NomeFantasiaCnpjPessoa")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("nomeFantasiaCnpjPessoa");

                    b.Property<string>("PorteEmpresaCnpjPessoa")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("porteEmpresaCnpjPessoa");

                    b.Property<string>("RazaoSocialCnpjPessoa")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("razaoSocialCnpjPessoa");

                    b.Property<string>("RgCpfPessoa")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("rgCpfPessoa");

                    b.Property<string>("TelefoneCpfPessoa")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("telefoneCpfPessoa");

                    b.Property<string>("TipoPessoa")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("tipoPessoa");

                    b.HasKey("IdPessoa");

                    b.HasIndex("CnpjCnpjPessoa")
                        .IsUnique()
                        .HasFilter("[cnpjCnpjPessoa] IS NOT NULL");

                    b.HasIndex("CpfCpfPessoa")
                        .IsUnique()
                        .HasFilter("[cpfCpfPessoa] IS NOT NULL");

                    b.HasIndex("IdUsuario")
                        .IsUnique();

                    b.ToTable("Pessoa");
                });

            modelBuilder.Entity("AeroHubAPI.Models.Piloto", b =>
                {
                    b.Property<int>("IdPiloto")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("idPiloto");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdPiloto"));

                    b.Property<DateTime>("DataCriacaoPiloto")
                        .HasColumnType("datetime2")
                        .HasColumnName("dataCriacaoPiloto");

                    b.Property<int>("IdPessoa")
                        .HasColumnType("int")
                        .HasColumnName("idPessoa");

                    b.Property<int>("IdUsuario")
                        .HasColumnType("int")
                        .HasColumnName("idUsuario");

                    b.Property<bool>("PlanoPremiumAtivadoPiloto")
                        .HasColumnType("bit")
                        .HasColumnName("planoPremiumAtivadoPiloto");

                    b.Property<DateTime?>("PlanoPremiumDesdePiloto")
                        .HasColumnType("datetime2")
                        .HasColumnName("planoPremiumDesdePiloto");

                    b.Property<string>("SobreMimPiloto")
                        .HasColumnType("TEXT")
                        .HasColumnName("sobreMimPiloto");

                    b.Property<string>("StatusContaPiloto")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("statusContaPiloto");

                    b.Property<string>("TituloProfissionalPiloto")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("tituloProfissionalPiloto");

                    b.HasKey("IdPiloto");

                    b.HasIndex("IdPessoa")
                        .IsUnique();

                    b.HasIndex("IdUsuario")
                        .IsUnique();

                    b.ToTable("Piloto");
                });

            modelBuilder.Entity("AeroHubAPI.Models.RepresentanteLegalCnpjPessoa", b =>
                {
                    b.Property<int>("IdRepresentanteLegal")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("idRepresentanteLegal");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdRepresentanteLegal"));

                    b.Property<string>("CargoRepresentanteLegalCnpjPessoa")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("cargoRepresentanteLegalCnpjPessoa");

                    b.Property<string>("CpfRepresentanteLegalCnpjPessoa")
                        .HasMaxLength(14)
                        .HasColumnType("nvarchar(14)")
                        .HasColumnName("cpfRepresentanteLegalCnpjPessoa");

                    b.Property<string>("EmailRepresentanteLegalCnpjPessoa")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("emailRepresentanteLegalCnpjPessoa");

                    b.Property<int>("IdPessoa")
                        .HasColumnType("int")
                        .HasColumnName("idPessoa");

                    b.Property<string>("NomeRepresentanteLegalCnpjPessoa")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("nomeRepresentanteLegalCnpjPessoa");

                    b.Property<string>("TelefoneRepresentanteLegalCnpjPessoa")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("telefoneRepresentanteLegalCnpjPessoa");

                    b.HasKey("IdRepresentanteLegal");

                    b.HasIndex("IdPessoa")
                        .IsUnique();

                    b.ToTable("RepresentanteLegalCnpjPessoa");
                });

            modelBuilder.Entity("AeroHubAPI.Models.Usuario", b =>
                {
                    b.Property<int>("IdUsuario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("idUsuario");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdUsuario"));

                    b.Property<DateTime?>("DataAceiteTermosUsuario")
                        .HasColumnType("datetime2")
                        .HasColumnName("dataAceiteTermosUsuario");

                    b.Property<DateTime>("DataCriacaoControleUsuario")
                        .HasColumnType("datetime2")
                        .HasColumnName("dataCriacaoControleUsuario");

                    b.Property<string>("EmailUsuario")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("emailUsuario");

                    b.Property<string>("SenhaUsuario")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("senhaUsuario");

                    b.Property<string>("StatusContaUsuario")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("statusContaUsuario");

                    b.Property<bool>("TermosAceitosUsuario")
                        .HasColumnType("bit")
                        .HasColumnName("termosAceitosUsuario");

                    b.Property<string>("TipoCadastroUsuario")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("tipoCadastroUsuario");

                    b.HasKey("IdUsuario");

                    b.HasIndex("EmailUsuario")
                        .IsUnique();

                    b.ToTable("Usuario");
                });

            modelBuilder.Entity("AeroHubAPI.Models.Carteira", b =>
                {
                    b.HasOne("AeroHubAPI.Models.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("IdUsuario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("AeroHubAPI.Models.Contratante", b =>
                {
                    b.HasOne("AeroHubAPI.Models.Pessoa", "Pessoa")
                        .WithMany()
                        .HasForeignKey("IdPessoa")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AeroHubAPI.Models.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("IdUsuario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Pessoa");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("AeroHubAPI.Models.DocumentoPessoa", b =>
                {
                    b.HasOne("AeroHubAPI.Models.Pessoa", "Pessoa")
                        .WithMany()
                        .HasForeignKey("IdPessoa")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Pessoa");
                });

            modelBuilder.Entity("AeroHubAPI.Models.Endereco", b =>
                {
                    b.HasOne("AeroHubAPI.Models.Pessoa", "Pessoa")
                        .WithMany()
                        .HasForeignKey("IdPessoa")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Pessoa");
                });

            modelBuilder.Entity("AeroHubAPI.Models.Pessoa", b =>
                {
                    b.HasOne("AeroHubAPI.Models.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("IdUsuario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("AeroHubAPI.Models.Piloto", b =>
                {
                    b.HasOne("AeroHubAPI.Models.Pessoa", "Pessoa")
                        .WithMany()
                        .HasForeignKey("IdPessoa")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AeroHubAPI.Models.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("IdUsuario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Pessoa");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("AeroHubAPI.Models.RepresentanteLegalCnpjPessoa", b =>
                {
                    b.HasOne("AeroHubAPI.Models.Pessoa", "Pessoa")
                        .WithMany()
                        .HasForeignKey("IdPessoa")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Pessoa");
                });
#pragma warning restore 612, 618
        }
    }
}
